name: 'msxml4'
description: 'install msxml4 on a windows server'
branding:
  icon: 'code'  
  color: 'red'
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/msxml4-install.ps1
      shell: pwsh